apiVersion: apps/v1
kind: Deployment
metadata:
  name: tirthankara
spec:
  replicas: 2  # Two replicas for high availability
  selector:
    matchLabels:
      app: tirthankara
  template:
    metadata:
      labels:
        app: tirthankara
    spec:
      containers:
      - name: tirthankara
        image: 192.168.86.39:30500/tirthankara:v2 
        ports:
        - containerPort: 5001
        env:
        - name: STABILITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: stability-api-secret
              key: api-key
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi