apiVersion: v1
kind: Service
metadata:
  name: tirthankara
spec:
  type: NodePort
  selector:
    app: tirthankara
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30501  # Unique port for external access